openapi: 3.0.3
info:
  title: Lethean VPN server OpenAPI
  description: |-
    This is Lethean VPN API definition
  license:
      name: GPLv3
  version: "1.1"

paths:
  /api/vdp:
    get:
      summary: Get VDP
      description: Get VPN Description Protocol containing all Spaces and Gateways
      operationId: getVdp
      parameters:
        - in: query
          name: localOnly
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vdp'
        '500':
          description: Server error
    post:
      summary: Post new VDP to server
      description: Post new VDP to server
      operationId: pushVdp
      parameters:
        - in: query
          name: checkOnly
          schema:
            type: boolean
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vdp'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VdpSaveStatus'
        '401':
          description: Access token is missing or invalid
        '402':
          description: Access token is missing or invalid
        '403':
          description: Access token is missing or invalid
        '443':
          description: Error in VDP
        '500':
          description: Server error

  /api/session:
    post:
      summary: Prepare session to connect to Space using Gate
      description: Prepare session to connect to Space using Gate
      operationId: Session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SessionRequest'
      responses:
        '200':
          description: Connected
        '400':
          description: Bad request
        '402':
          description: Waiting for payment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
        '460':
          description: Unknown/bad space
        '461':
          description: Unknown/bad gate
        '462':
          description: Cannot use this space/gate combination
        '463':
          description: No permission to reuse session
        '464':
          description: Cannot reuse with different gate or space
        '465':
          description: Missing WG endpoint data
        '500':
          description: Server error
    get:
      summary: Get session info
      description: Get info about session
      operationId: getSession
      parameters:
        - in: query
          name: sessionid
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
        '400':
          description: Missing sessionid
        '402':
          description: Waiting for payment
        '404':
          description: Session not found
        '500':
          description: Server error

  /api/sessions:
    get:
      summary: Get server sessions
      description: Get sessions. This means all prepaid sessions, some of them can be connected, some disconnected
      operationId: getSessions
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: active
          schema:
            type: boolean
            default: False
        - in: query
          name: notpaid
          schema:
            type: boolean
            default: False
        - in: query
          name: expired
          schema:
            type: boolean
            default: False
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sessions'
        '401':
          description: Access token is missing or invalid
        '402':
          description: Access token is missing or invalid
        '403':
          description: Access token is missing or invalid
        '500':
          description: Server error

  /api/pay/stripe:
    get:
      summary: Get Link for the Stripe payment
      description: Get Link for the Stripe payment
      operationId: stripePayment
      parameters:
        - in: query
          name: paymentid
          schema:
            type: string
        - in: query
          name: wallet
          schema:
            type: string
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad parameters
        '500':
          description: Server error
        '501':
          description: Cannot contact market API
        '502':
          description: Cannot use Stripe now. Please try again later

components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  schemas:

# Openapi providers definition
###################################

    Provider:
      type: object
      additionalProperties: false
      properties:
        file_type:
          type: string
          enum:
            - LetheanProvider
        file_version:
          type: string
          enum:
            - "1.1"
        revision:
          type: number
          default: 0
        ttl:
          type: number
          default: 0
        providerid:
          type: string
        owner:
          type: string
        name:
          type: string
        description:
          type: string
        ca:
          type: array
          items:
            type: string
        manager-url:
          type: string
        spaces:
          type: array
          items:
            type: string
        wallet:
          type: string
      required:
        - file_type
        - file_version
        - providerid
        - name
        - manager-url
        - spaces
        - ca

    Providers:
      type: array
      items:
        $ref: '#/components/schemas/Provider'
# Gate openapi specifications
###################################

    Gate:
      type: object
      additionalProperties: false
      properties:
        file_type:
          type: string
          enum:
            - LetheanGateway
        file_version:
          type: string
          enum:
            - "1.1"
        revision:
          type: number
          default: 0
        ttl:
          type: number
          default: 0
        providerid:
          type: string
        gateid:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: object
          additionalProperties: false
          properties:
            per-day:
              type: number
        internal:
          type: boolean
          default: false
        type:
          type: string
          enum:
            - wg
            - http-proxy
            - socks-proxy
            - daemon-rpc-proxy
            - daemon-p2p-proxy
            - wg-tcp
            - ssh
            - tls-ssh
        wg:
          type: object
          additionalProperties: false
          properties:
            endpoint:
              type: string
            tcp:
              type: boolean
              default: false
            public_key:
              type: string
            ipv4_network:
              type: string
            ipv4_gateway:
              type: string
            ipv6_network:
              type: string
            ipv6_gateway:
              type: string
          required:
            - endpoint
            - public_key
            - ipv4_network
            - ipv4_gateway
        http-proxy:
          type: object
          additionalProperties: false
          properties:
            host:
              type: string
            port:
              type: integer
            tls:
              type: boolean
        socks-proxy:
          type: object
          additionalProperties: false
          properties:
            host:
              type: string
            port:
              type: integer
            tls:
              type: boolean
        daemon-p2p-proxy:
          type: object
          additionalProperties: false
          properties:
            host:
              type: string
            port:
              type: integer
            tls:
              type: boolean
            coin:
              type: string
              default: lethean
              enum:
                - lethean
                - monero
        daemon-rpc-proxy:
          type: object
          additionalProperties: false
          properties:
            host:
              type: string
            port:
              type: integer
            tls:
              type: boolean
            coin:
              type: string
              default: lethean
              enum:
                - lethean
                - monero
        ssh:
          type: object
          additionalProperties: false
          properties:
            host:
              type: string
            port:
              type: integer
            username:
              type: string
            tls:
              type: boolean
          required:
            - host
            - port
            - username
        spaces:
          type: array
          items:
            type: string
        gates:
          type: array
          items:
            type: string
        replaces:
          type: string
        gate-types:
          type: array
          items:
            type: string
            enum:
              - wg
              - http-proxy
              - socks-proxy
              - daemon-rpc
              - daemon-p2p
              - wg-tcp
              - ssh
              - ssh-tls
      required:
        - gateid
        - name
        - providerid
        - file_version
        - file_type
        - type
        - spaces

    Gates:
      type: array
      items:
        $ref: '#/components/schemas/Gate'
# Openapi space definition
###################################

    Space:
      type: object
      additionalProperties: false
      properties:
        file_type:
          type: string
          enum:
            - LetheanSpace
        file_version:
          type: string
          enum:
            - "1.1"
        revision:
          type: number
          default: 0
        ttl:
          type: number
          default: 0
        providerid:
          type: string
        spaceid:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: object
          additionalProperties: false
          properties:
            per-day:
              type: number
        ipv4_networks:
          type: array
          items:
            type: string
        ipv6_networks:
          type: array
          items:
            type: string
        dns_servers:
          type: array
          items:
            type: string
      required:
        - spaceid
        - providerid
        - file_type
        - file_version
        - dns_servers
        - price
        - ipv4_networks
        - ipv6_networks

# Session definition
###################################

    Session:
      type: object
      additionalProperties: false
      properties:
        spaceid:
          type: string
        gateid:
          type: string
        created:
          type: integer
        username:
          type: string
        password:
          type: string
        bearer:
          type: string
        wallet:
          type: string
        price:
          type: number
        days:
          type: integer
        paid:
          type: boolean
        parent:
          type: string
        payments:
          type: array
          items:
            $ref: '#/components/schemas/Payment'
        paymentid:
          type: string
        activated:
          type: integer
        payment_sent:
          type: string
        wg:
          $ref: '#/components/schemas/WgSessionData'
        proxy:
          $ref: '#/components/schemas/ProxySessionData'
        ssh:
          $ref: '#/components/schemas/SSHSessionData'
        sessionid:
          type: string
        expires:
          type: integer
      required:
        - created
        - sessionid
        - paymentid
        - wallet
        - price
        - days
        - expires

    Sessions:
      type: array
      items:
        $ref: '#/components/schemas/Session'

    Payment:
      type: object
      additionalProperties: false
      properties:
        height:
          type: number
        txid:
          type: string
        amount:
          type: number

    SessionRequest:
      type: object
      additionalProperties: false
      properties:
        spaceid:
          type: string
        gateid:
          type: string
        days:
          type: integer
        like_sessionid:
          type: string
        wg:
          $ref: '#/components/schemas/WgSessionRequestData'
      required:
        - spaceid
        - gateid
        - days

    WgSessionRequestData:
      type: object
      additionalProperties: false
      properties:
        endpoint:
          type: string
          default: dynamic
        public_key:
          type: string
        network:
          type: object
          additionalProperties: false
          properties:
            requested_ipv4_prefix:
              type: number
      required:
        - public_key

    WgSessionData:
      type: object
      additionalProperties: false
      properties:
        client_endpoint:
          type: string
        client_public_key:
          type: string
        server_public_key:
          type: string
        psk:
          type: string
        client_ipv4_address:
          type: string
        ipv4_prefix:
          type: integer
        server_ipv4_address:
          type: string
        dns:
          type: array
          items:
            type: string
        client_ipv4_networks:
          type: array
          items:
            type: string
        server_ipv4_networks:
          type: array
          items:
            type: string
      required:
        - client_public_key
        - server_public_key
        - client_ipv4_address
        - ipv4_prefix
        - psk
        - server_ipv4_address

    ProxySessionData:
      type: object
      additionalProperties: false
      properties:
        key:
          type: string
        crt:
          type: string
      required:
        - key
        - crt

    SSHSessionData:
      type: object
      additionalProperties: false
      properties:
        key:
          type: string
        crt:
          type: string
        port:
          type: number
      required:
        - key
        - crt

# Openapi VDP definition
###################################

    Vdp:
      type: object
      additionalProperties: false
      properties:
        file_type:
          type: string
          enum:
            - VPNDescriptionProtocol
        file_version:
          type: string
          enum:
            - "1.1"
        spaces:
          type: array
          items:
            $ref: '#/components/schemas/Space'
        gates:
          type: array
          items:
            $ref: '#/components/schemas/Gate'
        providers:
          type: array
          items:
            $ref: '#/components/schemas/Provider'
        signatures:
          type: array
      required:
        - file_type
        - file_version

    VdpSaveStatus:
      type: object
      additionalProperties: false
      properties:
        saved_gates:
          type: number
        saved_spaces:
          type: number
        saved_providers:
          type: number
        ignored_gates:
          type: number
        ignored_spaces:
          type: number
        ignored_providers:
          type: number
